# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-08 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mxhacks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='law',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='procedure',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tags',
            name='img',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='tags',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
