# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-08 15:24
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mxhacks', '0002_auto_20180908_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='law',
            name='bullets',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=50, null=True), default=[], size=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='procedure',
            name='steps',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=50, null=True), default=[], size=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='law',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
