# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-08 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mxhacks', '0002_auto_20180908_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='law',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
